# Generated by Django 5.2.12 on 2026-05-20 05:23

import apps.processing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='AC Machines Lab', max_length=200)),
                ('course_code', models.CharField(default='C0213', max_length=50)),
                ('department', models.CharField(default='B.Tech. - EEE', max_length=100)),
                ('regulation', models.CharField(default='MR22', max_length=50)),
                ('faculty_name', models.CharField(default='Dr. P. Marimuthu', max_length=200)),
                ('academic_year', models.CharField(default='2025-2026', max_length=50)),
                ('year_admitted', models.CharField(default='2025  -  2026', max_length=50)),
                ('class_name', models.CharField(default='III YEAR /V SEM', max_length=100)),
                ('total_students', models.IntegerField(default=66)),
                ('co_po_mapping', models.JSONField(default=apps.processing.models.get_default_co_po_mapping)),
                ('survey_inputs', models.JSONField(default=apps.processing.models.get_default_survey_inputs)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('student_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co1_attainment', models.FloatField(default=0.0)),
                ('co2_attainment', models.FloatField(default=0.0)),
                ('co3_attainment', models.FloatField(default=0.0)),
                ('co4_attainment', models.FloatField(default=0.0)),
                ('co5_attainment', models.FloatField(default=0.0)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='processing.uploadedfile')),
            ],
        ),
    ]
